---
- name: Установка Kibana
  hosts: kibana_srv
  become: yes
  vars:
    elastic_httphost: 10.10.3.4:9200
  tasks:

  - name: Установка пакета kibana
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.15.1-amd64.deb"

  - name: Копируем конфигурационный файл kibana
    template:
      src: /home/vb/Netology_Diplom/ansible/kibana.j2
      dest: /etc/kibana/kibana.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name:  Перезапускаем kibana и добавляем в автозагрузку
    service:
      name: kibana
      state: restarted
      enabled: yes
